### ISSUE TITLE
[1.0] Ability to define a custom countCondition

### ISSUE THREAD

**Issue by tm1000** [Laragear/Preload#3]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

It would be nice if we were able to define a custom countCondition (https://github.com/Laragear/Preload/blob/1.x/src/Condition.php#L58)

The reason being is that my instance of Laravel runs in docker and I have a healthchecker running which means the healthchecker GETs a url every minute. This causes Preload to hit the 10,000 limit every 10,000 seconds regardless of if I have traffic or not.

I'm willing to do a PR for this if needed

### Code sample

```php
See https://github.com/Laragear/Preload/blob/1.x/src/Condition.php#L58
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by tm1000** [comment]
Actually ignore this. I didnt realize that by defining the condition though the static callback I am actually overwriting `countCondition` itself!

**Comment by DarkGhostHunter** [comment]
[I was just going to point out this](https://github.com/Laragear/Preload#custom-condition).
